[project]
name = "cakeordog"
version = "0.1.0"
description = "Classificator for Muffin vs chihuahua dataset https://www.kaggle.com/datasets/samuelcortinhas/muffin-vs-chihuahua-image-classification/data"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy>=1.24.0"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
]
ignore = [
  "E501", # line too long
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # unused import at __init__.py

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=src/cakeordog --cov-report=term-missing --cov-report=html"

[dependency-groups]
dev = [
  "black>=24.8.0",
  "mypy>=1.14.1",
  "pytest>=8.3.5",
  "pytest-cov>=5.0.0",
  "ruff>=0.14.8",
  "sphinx>=7.1.2",
  "sphinx-rtd-theme>=0.5.1",
]

[project.scripts]
cakeordog = "cakeordog.calculator:main"
